feat(all): advance components module
fmayorgad/Epam_ReactJS_NetflixRoulette pull request #4
Opened 2023-04-16 02:21 UTC by fmayorgad

2023-04-18 04:00 UTC, jgmurillo10 requested changes
Amazing work! 🔥 could you take a look at the tests?

2023-04-18 04:00 UTC, jgmurillo10 commented on src/stories/MovieForm.stories.js
> +import { MovieForm } from '../Components/MovieForm/MovieForm';
Amazing work adding several scenarios! 😎

2023-04-18 04:00 UTC, jgmurillo10 commented on src/stories/MovieForm.stories.js
> +    confirmHandler
It looks like `handleAction` undefined throws error on this storybook

2023-04-18 04:00 UTC, jgmurillo10 commented on public/styles.css
> +  background: #f65261;
You could use CSS custom properties to handle variables or SASS preprocessor for handling variables as well

2023-04-18 04:00 UTC, jgmurillo10 commented on src/Components/CustomDialog/CustomDialog.css
> +.customDialogContainer{
This and line 5 are the same class

2023-04-18 04:00 UTC, jgmurillo10 commented on src/Components/CustomDialog/CustomDialog.css
> +.customDialogTitle{
Let's standardize spacing before braces :) 
`title {`

2023-04-18 04:00 UTC, jgmurillo10 commented on src/Components/CustomDialog/CustomDialog.js
> +                                <svg focusable="false" aria-hidden="true" viewBox="0 0 24 24">
You could store `SVGs` as files and `require` them.

2023-04-18 04:00 UTC, jgmurillo10 commented on src/Components/MovieForm/MovieForm.css
> +.movieFormFieldContainerLarge {
This class is repeated on line 14

2023-04-18 04:00 UTC, jgmurillo10 commented on src/Components/MovieForm/MovieForm.js
> +            title: props.title ? props.title : '',
You could use `nullish` operrator `??` instead of ternary
```
title: props.title ?? '',
...
```

2023-04-18 04:00 UTC, jgmurillo10 commented on src/Components/SearchForm/SearchForm.css
> +searchFormContainer form{
This class is repeated on line 50

2023-04-18 04:00 UTC, jgmurillo10 commented on src/Components/DeleteMovieForm/DeleteMovieform.js
> +        console.log(props)
Remove logs pleease

2023-04-19 10:09 UTC, fmayorgad commented on src/Components/DeleteMovieForm/DeleteMovieform.js
> +        console.log(props)
Done

2023-04-19 10:11 UTC, fmayorgad commented on src/Components/MovieForm/MovieForm.js
> +            title: props.title ? props.title : '',
Good approach!

2023-04-19 10:15 UTC, fmayorgad commented on src/stories/MovieForm.stories.js
> +    confirmHandler
It work for delete, but was failing for add because I didn't pass the onSubmit in params

2023-04-19 10:18 UTC, fmayorgad commented on public/styles.css
> +  background: #f65261;
got it, I am going to implement styled componment, so I will add that when implementing

2023-04-19 10:19 UTC, fmayorgad commented on public/styles.css
> +  background: #f65261;
Yes, my mistake. I was trying to add a default-styles to comsume with Storybook

2023-04-19 10:20 UTC, fmayorgad commented on src/Components/CustomDialog/CustomDialog.css
> +.customDialogTitle{
Done!

2023-04-19 10:20 UTC, fmayorgad commented on src/Components/CustomDialog/CustomDialog.js
> +                                <svg focusable="false" aria-hidden="true" viewBox="0 0 24 24">
In this case, I prefered to added directly for not to have to handle with import error with jest

2023-04-19 10:21 UTC, fmayorgad commented on src/Components/MovieForm/MovieForm.css
> +.movieFormFieldContainerLarge {
You are right!

2023-04-19 10:21 UTC, fmayorgad commented on src/Components/SearchForm/SearchForm.css
> +searchFormContainer form{
Removed!

2023-04-19 10:22 UTC, fmayorgad commented on src/Components/DeleteMovieForm/DeleteMovieform.js
> +        console.log(props)
Done!

2023-04-19 10:24 UTC, fmayorgad commented on src/Components/CustomDialog/CustomDialog.css
> +.customDialogContainer{
Removed!

2023-04-19 10:24 UTC, fmayorgad commented on src/stories/MovieForm.stories.js
> +import { MovieForm } from '../Components/MovieForm/MovieForm';
Thanks!

2023-04-23 21:51 UTC, merged